### ISSUE TITLE
TypeError: Object 'Armature' is not a MESH

### ISSUE THREAD

**Issue by Iplay4u** [parrygod1/Physics-to-Bones#1]
Hi there, I might be dumb and not using it correctly but I ran into this issue on Blender V.3.4.1. I tried using the scrypt on the armature as well as the mesh object, but it threw back the same error:

`Python: Traceback (most recent call last):
  File "C:\Users\[User]\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\object_physicstobones\__init__.py", line 163, in execute
    main(self, context)
  File "C:\Users\[User]\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\object_physicstobones\__init__.py", line 49, in main
    objectList = [obj for obj in bpy.context.collection.objects if ptb.checkIfValidType(obj, 'MESH')]
  File "C:\Users\[User]\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\object_physicstobones\__init__.py", line 49, in <listcomp>
    objectList = [obj for obj in bpy.context.collection.objects if ptb.checkIfValidType(obj, 'MESH')]
  File "C:\Users\[User]\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\object_physicstobones\ptb.py", line 20, in checkIfValidType
    raise TypeError("Object '%s' is not a %s" % (object.name, desired_type))
TypeError: Object 'Armature' is not a MESH`

**Comment by parrygod1** [comment]
Hey, try deselecting everything, then select only the meshes you need and run the script.
